# Generated by Django 5.1.6 on 2025-02-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timer',
            new_name='TimeEntry',
        ),
    ]
